spring.datasource.url=jdbc:postgresql://localhost:5433/telegram_bot
spring.datasource.username=postgres
spring.datasource.password=4683
bot.name=InnaSkyPro_Bot
telegram.bot.token=7564181101:AAGMkIOfKlMWtSSvb1SLFisx_VT4ULv1e8I

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml